# TENSORS

## INITIALIZING TENSORS

there are three ways we can initialize tensors:

1. from data
2. from a numpy array
3. from another tensor

### FROM DATA

In [3]:
import torch
data = [1,2]
tensor_data = torch.tensor(data)
print(tensor_data)
print(data)

data = [[1,2],[3,4]]
tensor_data = torch.tensor(data)
print(tensor_data)
print(data)

tensor([1, 2])
[1, 2]
tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]


### FROM A NUMPY ARRAY

what is a numpy array:- A NumPy array is a fast, fixed-type, multidimensional container for numerical data, while a normal array (Python list) is a slower, general-purpose container that can hold any type of object.

In [4]:
import numpy as np
np_array = np.array(data)
tensor_data = torch.from_numpy(np_array)
print(tensor_data)

tensor([[1, 2],
        [3, 4]])


### FROM ANOTHER TENSOR


In [5]:
x_ones = torch.ones_like(tensor_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4226, 0.7254],
        [0.0384, 0.7140]]) 



### FROM A RANDOM VALUE

In [6]:
import torch
tensor = torch.rand(3,4)
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Random Tensor: \n {tensor} \n")
tensor = torch.rand(1,2)
print(f"Random Tensor: \n {tensor} \n")
tensor = torch.rand(7, 7, 3)
print(f"Random Tensor: \n {tensor} \n")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Random Tensor: 
 tensor([[0.5767, 0.3843, 0.4461, 0.9649],
        [0.4307, 0.2566, 0.9705, 0.7395],
        [0.6076, 0.3879, 0.9592, 0.2914]], device='cuda:0') 

Random Tensor: 
 tensor([[0.8086, 0.1832]]) 

Random Tensor: 
 tensor([[[0.6382, 0.2010, 0.7416],
         [0.9119, 0.8843, 0.4974],
         [0.1246, 0.0517, 0.5983],
         [0.3262, 0.5741, 0.0794],
         [0.9030, 0.6713, 0.6933],
         [0.3922, 0.9196, 0.5593],
         [0.5430, 0.1647, 0.8529]],

        [[0.9842, 0.2971, 0.7742],
         [0.8143, 0.3724, 0.6948],
         [0.7140, 0.3671, 0.9986],
         [0.7937, 0.0432, 0.6015],
         [0.0150, 0.7881, 0.6987],
         [0.3225, 0.6765, 0.9888],
         [0.5159, 0.5959, 0.3561]],

        [[0.8868, 0.0678, 0.8880],
         [0.1542, 0.4653, 0.3022],
         [0.0168, 0.8672, 0.4076],
         [0.6149, 0.7346, 0.1885],
         [0.5481, 0.0497, 0.4272],
         [0.0019, 0.2331, 0.5725],
         [0.9382, 0.4021, 0.8688]],

        [[0.8523, 0.6944, 0.5840]