# TENSORS

## INITIALIZING TENSORS

there are three ways we can initialize tensors:

1. from data
2. from a numpy array
3. from another tensor

### FROM DATA

In [3]:
import torch
data = [1,2]
tensor_data = torch.tensor(data)
print(tensor_data)
print(data)

data = [[1,2],[3,4]]
tensor_data = torch.tensor(data)
print(tensor_data)
print(data)

tensor([1, 2])
[1, 2]
tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]


### FROM A NUMPY ARRAY

what is a numpy array:- A NumPy array is a fast, fixed-type, multidimensional container for numerical data, while a normal array (Python list) is a slower, general-purpose container that can hold any type of object.

In [4]:
import numpy as np
np_array = np.array(data)
tensor_data = torch.from_numpy(np_array)
print(tensor_data)

tensor([[1, 2],
        [3, 4]])


### FROM ANOTHER TENSOR


In [5]:
x_ones = torch.ones_like(tensor_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4226, 0.7254],
        [0.0384, 0.7140]]) 

