In [1]:
import torch
print(torch.__version__)

2.4.0+cpu


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.float64)

In [4]:
torch.get_default_dtype()

torch.float64

In [5]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])

In [6]:
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.is_tensor(tensor_arr)

True

In [8]:
torch.numel(tensor_arr) # this is for number of elements

6

In [9]:
torch.Tensor(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [10]:
torch.rand(2,2)

tensor([[0.2499, 0.9118],
        [0.8538, 0.0710]])

In [11]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [12]:
torch.ones([2,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
torch.zeros_like(torch.ones([2,4]))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
torch.eye(5) # creates a square matrix with the main diagonal equal to one

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.nonzero(torch.eye(2)) # index for our non-zero elements in a matrix

tensor([[0, 0],
        [1, 1]])

In [16]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [17]:
torch.tensor(torch.eye(3)) #small case tensor is used to copy data

/tmp/ipykernel_36/1067749376.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(torch.eye(3)) #small case tensor is used to copy data


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
initial_tensor = torch.rand(3,4)
initial_tensor.size()

torch.Size([3, 4])

In [19]:
initial_tensor

tensor([[0.2307, 0.0548, 0.7317, 0.2688],
        [0.0040, 0.1396, 0.9793, 0.5719],
        [0.4481, 0.7117, 0.5717, 0.6722]])

In [20]:
initial_tensor.fill_(10) # replace the elements with 10, _ means it is an inplace tensor, which means, replace the actual tensor with this new value

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [21]:
new_tensor = initial_tensor.add(15) # for every value, add 15 to individual tensor values
new_tensor

tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]])

In [22]:
new_tensor.sqrt_()

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [23]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [34]:
tensor_chunk = torch.chunk(x,3,0 ) # chunks the dimensions to three tensors
tensor_chunk
x.size()
tensor_chunk[1].size()

torch.Size([5])

In [35]:
tensor_concat = torch.cat((tensor_chunk[1], tensor_chunk[0],tensor_chunk[2]), 0)
tensor_concat
print(tensor_concat)
print(tensor_concat.size())
tensor_concat.size()

tensor([ 3.6357,  4.3429,  5.0500,  5.7571,  6.4643,  0.1000,  0.8071,  1.5143,
         2.2214,  2.9286,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])
torch.Size([15])


torch.Size([15])

In [46]:
random_tensor = torch.Tensor([[10,20,30],[30,49,76],[12,34,65]])
random_tensor

tensor([[10., 20., 30.],
        [30., 49., 76.],
        [12., 34., 65.]])

In [47]:
random_tensor[0][1] #or random_tensor[0, 1]
random_tensor[1,0]# accessing specific elements - indexing into tensors - it gives the results as tensors

tensor(30.)

In [48]:
print("All of the rows from index 1 to the end")
print(random_tensor[1:])
print("All of the rows from the row 1 and all columns from row 1 onwards")
print(random_tensor[1:,1: ])

All of the rows from index 1 to the end
tensor([[30., 49., 76.],
        [12., 34., 65.]])
All of the rows from the row 1 and all columns from row 1 onwards
tensor([[49., 76.],
        [34., 65.]])


In [49]:
random_tensor.size()
print(random_tensor.view(9))
print(random_tensor)


tensor([10., 20., 30., 30., 49., 76., 12., 34., 65.])
tensor([[10., 20., 30.],
        [30., 49., 76.],
        [12., 34., 65.]])


In [51]:
random_tensor = torch.rand(12)
print(random_tensor)
print(random_tensor.view(2,6))# changing shape to see how the tensor will behave on different dimensions
print(random_tensor.view(4,3))

tensor([0.0579, 0.5235, 0.1822, 0.9609, 0.8851, 0.5347, 0.4942, 0.6947, 0.0342,
        0.5060, 0.3617, 0.9174])
tensor([[0.0579, 0.5235, 0.1822, 0.9609, 0.8851, 0.5347],
        [0.4942, 0.6947, 0.0342, 0.5060, 0.3617, 0.9174]])
tensor([[0.0579, 0.5235, 0.1822],
        [0.9609, 0.8851, 0.5347],
        [0.4942, 0.6947, 0.0342],
        [0.5060, 0.3617, 0.9174]])


In [52]:
random_tensor.shape

torch.Size([12])

In [54]:
random_tensor.size()

torch.Size([12])

To add and remove dimensions,we can use squeeze and unsqueezed random variables

In [55]:
twobyfour_tensor = torch.rand(2,4)
print(twobyfour_tensor)

tensor([[0.8955, 0.8531, 0.4919, 0.6088],
        [0.6919, 0.2411, 0.7645, 0.3688]])


In [69]:
unsqueezed = torch.unsqueeze(twobyfour_tensor, 2)# add dimensions at index 2, inner most 
print(twobyfour_tensor)
unsqueezed.size()

tensor([[0.8955, 0.8531, 0.4919, 0.6088],
        [0.6919, 0.2411, 0.7645, 0.3688]])


torch.Size([2, 4, 1])

In [71]:
sorted_tensors, sorted_indices = torch.sort(twobyfour_tensor)
sorted_tensors, sorted_indices

(tensor([[0.4919, 0.6088, 0.8531, 0.8955],
         [0.2411, 0.3688, 0.6919, 0.7645]]),
 tensor([[2, 3, 1, 0],
         [1, 3, 0, 2]]))

In [77]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
print(torch.unsqueeze(tensor_float, 0))
print(torch.squeeze(tensor_float, 0))
tensor_float

tensor([[-1.1000, -2.2000,  3.3000]], dtype=torch.float32)
tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)


tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [78]:
torch.abs(tensor_float) # absolute value

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [81]:
rand1 = torch.rand(2,3)
print(rand1)
rand2 = torch.rand([2,3])
rand2

tensor([[0.6546, 0.5344, 0.9912],
        [0.3299, 0.0283, 0.6455]])


tensor([[0.3145, 0.0540, 0.2045],
        [0.5622, 0.4174, 0.3825]])

In [92]:
print(rand1 + rand2) # element wise operations
print(torch.add(rand1, rand2))
print(torch.abs(rand1 - rand2))
print(torch.sub(rand1, rand2))
print(torch.div(rand1, rand2))
print(torch.mul(rand2, rand1))
print(torch.clamp(rand2, min = 1.2, max = 2)) # constrains your tensors to specific range - min and max range values

tensor([[0.9691, 0.5884, 1.1956],
        [0.8921, 0.4457, 1.0281]])
tensor([[0.9691, 0.5884, 1.1956],
        [0.8921, 0.4457, 1.0281]])
tensor([[0.3402, 0.4804, 0.7867],
        [0.2323, 0.3891, 0.2630]])
tensor([[ 0.3402,  0.4804,  0.7867],
        [-0.2323, -0.3891,  0.2630]])
tensor([[2.0819, 9.9006, 4.8474],
        [0.5868, 0.0677, 1.6875]])
tensor([[0.2059, 0.0288, 0.2027],
        [0.1855, 0.0118, 0.2469]])
tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])


In [100]:
t1 = torch.rand(2,3,5)
t3 = torch.rand(2,3,5)
t2 = torch.rand(5,3,2)
print(torch.mul(t1, t3))
print(torch.dot(torch.Tensor([1,2,3]), torch.Tensor([4,5,6]))) # sums them up to a scalar

tensor([[[0.1136, 0.4253, 0.0447, 0.3117, 0.6337],
         [0.0454, 0.6740, 0.1629, 0.0170, 0.4995],
         [0.6270, 0.0009, 0.4293, 0.2364, 0.8144]],

        [[0.0921, 0.2498, 0.4630, 0.5503, 0.1413],
         [0.5130, 0.2462, 0.1479, 0.0168, 0.3684],
         [0.4436, 0.1834, 0.6724, 0.0247, 0.4698]]])
tensor(32.)


VECTOR x MATRIX

In [107]:
torch.mv(torch.rand(2,3), torch.rand(3))

tensor([0.5959, 0.1754])

In [110]:
torch.mm(torch.rand(3,4), torch.rand(4,2))

tensor([[0.4803, 0.9606],
        [1.1531, 1.0892],
        [1.0095, 1.3704]])