CONVERSION FROM NUMPY ARRAYS TO TENSORS AND VICE-VERSA

tensors are numpy arrays that are capable of being executed on GPU, if you create a tensor from numpy array, and vice versa, they both share the same underlying memory

In [1]:
import numpy as np
import torch

In [5]:
tensor = torch.rand(3,4)
tensor.type

<function Tensor.type>

In [6]:
tensor.numpy() #converting a tensor to a numpy array

array([[0.84287834, 0.24366021, 0.24350655, 0.23659676],
       [0.96614605, 0.94884735, 0.34492838, 0.5470861 ],
       [0.1629138 , 0.05981064, 0.87461257, 0.71662575]], dtype=float32)

In [9]:
type(tensor.numpy())

numpy.ndarray

In [10]:
numpy_arr = np.array([[1.0, 2.0, 4.0],[1.2,3.9,5.6],[100.12, 123.23,143.54]])
numpy_arr

array([[  1.  ,   2.  ,   4.  ],
       [  1.2 ,   3.9 ,   5.6 ],
       [100.12, 123.23, 143.54]])

In [12]:
tensor_from_ndarray = torch.from_numpy(numpy_arr)
tensor_from_ndarray

tensor([[  1.0000,   2.0000,   4.0000],
        [  1.2000,   3.9000,   5.6000],
        [100.1200, 123.2300, 143.5400]], dtype=torch.float64)

In [13]:
type(tensor_from_ndarray)

torch.Tensor

In [15]:
torch.is_tensor(tensor_from_ndarray)

True